spring:
  application:
    name: lms-live-service

  datasource:
    url: jdbc:h2:mem:livedb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8084

livekit:
  api:
    key: devkey
    secret: devsecret

  server:
    url: ws://localhost:7880
    api-url: http://localhost:7880

  webhook:
    secret: devsecret